# SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

name: Comment Commands

on: issue_comment

jobs:
  comment-commands:
    uses: upbound/uptest/.github/workflows/provider-commands.yml@main
