# SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

name: Tag

on:
  workflow_dispatch: 
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  tag:
    uses: upbound/uptest/.github/workflows/provider-tag.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      message: ${{ github.event.inputs.message }}
